name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev gh-pages
      
      - name: Build project
        run: npm run build
      
      - name: Configure Git
        run: |
          git config --global user.name "uritisaiabhishek"
          git config --global user.email "uritisaiabhishek@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Use the GitHub token for authentication
        run: npx gh-pages -d dist -r https://$GH_TOKEN@github.com/uritisaiabhishek/todo-app.git # Replace <username> with your GitHub username
          